# Setup
title: "{versatile.effective.excellence.}"
email: gurmeetsbox dash learn@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  Resume etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swiftgurmeet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: swiftgurmeet
show_excerpts: true


# About/contact
author:
  name:       Gurmeet Singh
  url:        https://swiftgurmeet.github.io/

description: > # this means to ignore newlines until "baseurl:"
  Resume, projects, life
baseurl: ""
linkedin_username: gurmeet

category-list: [posts, pages, images, static]

#Static pages live here e.g. about.md
include: ['_pages']

#Others
markdown: kramdown

#google_analytics: [UA-122692016-1]

description: > # this means to ignore newlines until "baseurl:"

gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/posts/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
